### PR TITLE
basic support for 140plus characters  http://support.gnip.com/doing-m…

### PR DESCRIPTION
**Pull request by edashman**
…ore-with-140.html

Added support for the upcoming extended tweet feature http://support.gnip.com/doing-more-with-140.html taken from the official gnip4j fork.

### CODE REVIEW

**Comment by bw-matthew** [comment]
I don't understand why there are 6 json files (with a js extension) yet the test only uses one. Either way the code change seems straightforward.

**Comment by bw-matthew** [comment]
:+1: from me. It would be good for someone with more knowledge of our fork of this library to review it too.

**Comment by edashman** [comment]
I am confused by that too but it doesn't seem like a big enough deal to do anything about

**Comment by spmason** [comment]
Why are we maintaining our own fork of this library?

**Comment by edashman** [comment]
I can't remember why (thanos thinks it was something to do with serialisation), but @robstanley would probably know. There's about 60 odd commits difference since we diverged so if we do want to defork that's a job for another day.

**Comment by robstanley** [comment]
this is further complicated because this isn't even the branch we've been maintaining separately - the peerindex guys created this one because they weren't using gite. The version we actually have is further removed. I wonder if I can push the live branch of that repo to this repo to see if this pr will still merge with a different target?

**Pull request closed without merging**
